# Generated by Django 6.0.1 on 2026-02-03 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='health_status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Offline', 'Offline')], default='Healthy', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='last_reported',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('power_factor', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='parking.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
