# Generated by Django 6.0.1 on 2026-02-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_device_health_status_device_last_reported_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telemetrydata',
            unique_together={('device', 'timestamp')},
        ),
    ]
